version: '3.9'

services:
  database:
    container_name: database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432
    volumes:
      - hackcu-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres=value
  migration:
    container_name: migration
    build: ./backend
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/alembic/
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - hackcu-qdrant:/qdrant
    profiles:
      - local
    develop:
      watch:
        - action: rebuild
          path: ./qdrant/
  backend: 
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
      qdrant:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/
    
volumes:
  hackcu-database:
  hackcu-qdrant: