version: '3.9'

services:
  backend: 
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    develop:
      watch:
        - action: rebuild
          path: ./backend/